import { AppSidebar } from "@/components/app-sidebar";
import { BookOpenText, Code2, Container, ShieldCheck } from "lucide-react";

const endpoints = [
  ["Daftar artikel", "GET /api/v1/articles?category=teknologi&page=1&limit=10", "Wajib category. page mulai 1, limit maksimum 50."],
  ["Detail artikel", "GET /api/v1/articles/{slug}", "Mengembalikan content, SEO, kategori, tag, dan metadata publikasi."],
] as const;

const examples = {
  next: `const response = await fetch(\n  \`\${process.env.ARTIKEL_API_URL}/api/v1/articles?category=teknologi&page=1&limit=10\`,\n  {\n    headers: { "x-artikel-key": process.env.ARTIKEL_API_KEY! },\n    next: { revalidate: 60 },\n  },\n);\nconst { data, meta } = await response.json();`,
  vite: `// Browser hanya memanggil backend milik aplikasi.\n// Simpan ARTIKEL_API_KEY pada backend/serverless function.\nconst response = await fetch("/api/articles?category=teknologi");\nconst { data } = await response.json();`,
  laravel: `$response = Http::withHeaders([\n    'x-artikel-key' => config('services.artikel.key'),\n])->get(config('services.artikel.url') . '/api/v1/articles', [\n    'category' => 'teknologi', 'page' => 1, 'limit' => 10,\n]);\n$articles = $response->throw()->json('data');`,
  php: `$ch = curl_init('https://cms.carubra.com/api/v1/articles?category=teknologi&page=1&limit=10');\ncurl_setopt_array($ch, [\n    CURLOPT_RETURNTRANSFER => true,\n    CURLOPT_HTTPHEADER => ['x-artikel-key: ' . getenv('ARTIKEL_API_KEY')],\n]);\n$body = json_decode(curl_exec($ch), true);`,
  wordpress: `$response = wp_remote_get(ARTIKEL_API_URL . '/api/v1/articles?category=teknologi&page=1&limit=10', [\n    'headers' => ['x-artikel-key' => ARTIKEL_API_KEY],\n    'timeout' => 10,\n]);\n$articles = is_wp_error($response) ? [] :\n    (json_decode(wp_remote_retrieve_body($response), true)['data'] ?? []);`,
};

function CodeBlock({ children }: { children: string }) {
  return <pre className="mt-4 overflow-x-auto rounded-2xl bg-slate-950 p-4 text-xs leading-6 text-slate-200"><code>{children}</code></pre>;
}

export default function ApiDocsPage() {
  return <main className="min-h-screen bg-[#f5f7fb] p-3 text-slate-900 sm:p-5 lg:p-7"><div className="mx-auto grid max-w-[1800px] gap-5 lg:grid-cols-[240px_minmax(0,1fr)]"><AppSidebar/><section className="min-w-0"><header className="rounded-3xl bg-slate-950 px-5 py-7 text-white shadow-xl sm:px-8"><div className="flex items-start gap-4"><span className="rounded-2xl bg-violet-600 p-3"><BookOpenText size={24}/></span><div><p className="text-sm font-semibold text-violet-200">Developer documentation</p><h1 className="mt-1 text-3xl font-bold">API Artikel</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Deployment, autentikasi, endpoint, error, dan contoh integrasi untuk Next.js, Vite, Laravel, PHP, serta WordPress.</p></div></div></header>
  <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-5"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Mulai cepat</h2><p className="mt-2 text-sm leading-6 text-slate-600">Base URL <code className="rounded bg-slate-100 px-1.5 py-1">https://cms.carubra.com</code>. Kirim API key per website melalui header <code className="rounded bg-slate-100 px-1.5 py-1">x-artikel-key</code>.</p><CodeBlock>{`curl "https://cms.carubra.com/api/v1/articles?category=teknologi&page=1&limit=10" \\\n  -H "x-artikel-key: art_live_xxxxxxxxx"`}</CodeBlock></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Endpoint</h2><div className="mt-4 space-y-3">{endpoints.map(([title, endpoint, note]) => <article key={title} className="rounded-2xl border border-slate-200 p-4"><p className="font-semibold">{title}</p><code className="mt-2 block overflow-x-auto text-sm text-violet-700">{endpoint}</code><p className="mt-2 text-sm text-slate-500">{note}</p></article>)}</div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Next.js</h2><p className="mt-2 text-sm text-slate-600">Fetch dari Server Component atau Route Handler. Jangan gunakan prefix <code>NEXT_PUBLIC_</code> untuk key.</p><CodeBlock>{examples.next}</CodeBlock></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Vite dan SPA</h2><p className="mt-2 text-sm text-slate-600">Gunakan backend/serverless proxy. Variable <code>VITE_*</code> masuk bundle browser dan tidak aman untuk API key.</p><CodeBlock>{examples.vite}</CodeBlock></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Laravel dan PHP</h2><CodeBlock>{examples.laravel}</CodeBlock><CodeBlock>{examples.php}</CodeBlock></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">WordPress</h2><p className="mt-2 text-sm text-slate-600">Simpan URL dan key pada <code>wp-config.php</code>. Fetch dari theme/plugin menggunakan HTTP API WordPress.</p><CodeBlock>{examples.wordpress}</CodeBlock></section></div>
  <aside className="space-y-5"><section className="rounded-3xl border border-violet-100 bg-violet-50 p-5"><div className="flex items-center gap-2 font-bold text-violet-900"><ShieldCheck size={18}/> Keamanan</div><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700"><li>Key hanya server-side.</li><li>Key terpisah per environment.</li><li>Gunakan HTTPS.</li><li>Rotasi sebelum revoke key lama.</li></ul></section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 font-bold"><Container size={18}/> Deployment</div><CodeBlock>{`ssh maskhar@supabase-server\ncd ~/apps/cms-artikel\ngit pull\ndocker compose up -d --build\ndocker logs cms-artikel --tail 100`}</CodeBlock></section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 font-bold"><Code2 size={18}/> Rate limit</div><p className="mt-3 text-sm leading-6 text-slate-600">Default 120 request per 60 detik. Baca header <code>X-RateLimit-Remaining</code> dan hormati <code>Retry-After</code> saat status 429.</p></section></aside></div></section></div></main>;
}
