"use client";

import { AppSidebar } from "@/components/app-sidebar";
import { BookOpen, CheckCircle2, Clock3, FilePenLine, Plus } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type RecentArticle = { id: string; title: string; status: string; updated_at: string; categories: { name: string } | { name: string }[] | null; sites: { name: string } | { name: string }[] | null };
type DashboardData = { stats: { articles: number; inReview: number; published: number; activeCategories: number }; recent: RecentArticle[] };
const statusClass: Record<string, string> = { draft: "bg-slate-100 text-slate-600", in_review: "bg-amber-50 text-amber-700", revision_requested: "bg-orange-50 text-orange-700", approved: "bg-emerald-50 text-emerald-700", published: "bg-blue-50 text-blue-700", archived: "bg-slate-100 text-slate-500" };

export default function Home() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/cms/dashboard").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setDashboard(body.data); }).catch((error) => setMessage(error instanceof Error ? error.message : "Dashboard gagal dimuat.")); }, []);
  const stats = dashboard?.stats;
  const cards = [[FilePenLine, stats?.articles ?? 0, "Total artikel", "text-blue-600"], [Clock3, stats?.inReview ?? 0, "Menunggu review", "text-amber-600"], [CheckCircle2, stats?.published ?? 0, "Sudah terbit", "text-emerald-600"], [BookOpen, stats?.activeCategories ?? 0, "Kategori aktif", "text-violet-600"]] as const;
  return <main className="min-h-screen bg-[#f8fafc] p-4 text-slate-900 md:p-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[240px_1fr]"><AppSidebar/><section className="min-w-0"><header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-blue-600">Overview</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Dashboard editorial</h1><p className="mt-1 text-sm text-slate-500">Statistik sesuai website dan role pengguna aktif.</p></div><Link href="/articles/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/> Artikel baru</Link></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon, value, label, color]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={`inline-flex rounded-xl bg-slate-50 p-2 ${color}`}><Icon size={20}/></span><p className="mt-5 text-3xl font-bold">{value}</p><p className="mt-1 text-sm font-medium">{label}</p></article>)}</div><article className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-semibold">Artikel terbaru</h2><p className="mt-1 text-sm text-slate-500">Delapan artikel terakhir yang dapat diakses.</p></div><Link href="/articles" className="text-sm font-semibold text-blue-600">Lihat semua</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Artikel</th><th>Website</th><th>Kategori</th><th>Status</th><th className="px-5">Diperbarui</th></tr></thead><tbody>{dashboard?.recent.map((article) => { const category = Array.isArray(article.categories) ? article.categories[0] : article.categories; const site = Array.isArray(article.sites) ? article.sites[0] : article.sites; return <tr key={article.id} className="border-t border-slate-100"><td className="px-5 py-4 font-medium"><Link href={`/articles/${article.id}`} className="hover:text-blue-600">{article.title}</Link></td><td className="text-slate-500">{site?.name ?? "-"}</td><td className="text-slate-500">{category?.name ?? "-"}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass[article.status] ?? statusClass.draft}`}>{article.status.replace("_", " ")}</span></td><td className="px-5 text-slate-500">{new Date(article.updated_at).toLocaleString("id-ID")}</td></tr>; })}{dashboard && !dashboard.recent.length && <tr><td colSpan={5} className="p-10 text-center text-slate-500">Belum ada artikel.</td></tr>}</tbody></table></div></article>{message && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p>}</section></div></main>;
}
