import { AppSidebar } from "@/components/app-sidebar";
import Link from "next/link";
import { Plus, Search } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function ArticlesPage() {
  const supabase = await createClient();
  const { data: articles } = await supabase.schema("artikel").from("articles").select("id, title, slug, status, updated_at, categories(name)").order("updated_at", { ascending: false });
  return <main className="min-h-screen bg-[#f8fafc] p-5 md:p-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[240px_1fr]"><AppSidebar/><div className="min-w-0"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-blue-600">Konten</p><h1 className="mt-1 text-3xl font-bold">Artikel</h1><p className="mt-1 text-sm text-slate-500">Kelola draft dan publikasi semua artikel.</p></div><Link href="/articles/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/> Artikel baru</Link></div><div className="mt-7 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm text-slate-400"><Search size={17}/><input placeholder="Cari artikel..." className="w-full py-2 outline-none"/></label><select className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option>Semua status</option><option>Draft</option><option>In review</option><option>Published</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Judul</th><th>Kategori</th><th>Status</th><th>Diperbarui</th></tr></thead><tbody>{(articles ?? []).map((article) => <tr key={article.id} className="border-t border-slate-100"><td className="px-5 py-4"><Link href={`/articles/${article.id}`} className="font-semibold hover:text-blue-600">{article.title}</Link><p className="mt-1 text-xs text-slate-400">/{article.slug}</p></td><td className="text-slate-500">{((article.categories as unknown as { name: string }[] | null)?.[0]?.name) ?? "-"}</td><td><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{article.status.replace("_", " ")}</span></td><td className="text-slate-500">{new Date(article.updated_at).toLocaleDateString("id-ID")}</td></tr>)}</tbody></table>{!articles?.length && <div className="p-12 text-center text-sm text-slate-500">Belum ada artikel. Buat artikel pertama.</div>}</div></div></div></div></div></main>;
}



