"use client";
import { createClient } from "@/lib/supabase/client";
import { Plus, Puzzle, Trash2, UploadCloud } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
type Addon={id:string;addon_type:string;title:string;placement:string;config:Record<string,unknown>};type Gallery={id:string;name:string};
const types=["gallery","image_slider","pdf_viewer","video_embed","call_to_action","faq","related_articles","table_of_contents","highlight_box","file_download"];
export function ArticleAddonsPanel({articleId,siteId}:{articleId:string;siteId:string}){const[addons,setAddons]=useState<Addon[]>([]);const[galleries,setGalleries]=useState<Gallery[]>([]);const[type,setType]=useState("image_slider");const[galleryId,setGalleryId]=useState("");const[config,setConfig]=useState("{}");const[message,setMessage]=useState("");const[pdfPath,setPdfPath]=useState("");
async function load(){const[a,g]=await Promise.all([fetch(`/api/cms/articles/${articleId}/addons`).then(r=>r.json()),fetch(`/api/cms/galleries?siteId=${siteId}`).then(r=>r.json())]);setAddons(a.data??[]);setGalleries(g.data??[]);}useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[articleId,siteId]);
async function uploadPdf(file:File|undefined){if(!file)return;if(file.type!=="application/pdf"||file.size>20*1024*1024){setMessage("PDF maksimum 20 MB.");return;}const path=`${siteId}/${articleId}/addons/${crypto.randomUUID()}.pdf`;const{error}=await createClient().storage.from("artikel-media").upload(path,file,{contentType:file.type});if(error){setMessage(error.message);return;}setPdfPath(path);setMessage("PDF berhasil diupload.");}
async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);let parsed:Record<string,unknown>;try{parsed=JSON.parse(config);}catch{setMessage("Config JSON tidak valid.");return;}if(["gallery","image_slider"].includes(type))parsed={...parsed,gallery_id:galleryId};if(type==="pdf_viewer")parsed={...parsed,storage_path:pdfPath,show_download:true};const r=await fetch(`/api/cms/articles/${articleId}/addons`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({addonType:type,title:form.get("title"),placement:form.get("placement"),config:parsed})});const b=await r.json();setMessage(r.ok?"Add-on ditambahkan.":b.error);if(r.ok){event.currentTarget.reset();setConfig("{}");setPdfPath("");void load();}}
async function remove(id:string){if(!confirm("Hapus add-on ini?"))return;const r=await fetch(`/api/cms/articles/${articleId}/addons/${id}`,{method:"DELETE"});setMessage(r.ok?"Add-on dihapus.":"Add-on gagal dihapus.");if(r.ok)void load();}
return <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><Puzzle size={18}/><h2 className="font-semibold">Add-ons</h2></div><div className="mt-4 space-y-2">{addons.map(addon=><article key={addon.id} className="flex items-start justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><p className="text-sm font-semibold">{addon.title||addon.addon_type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-500">{addon.addon_type} · {addon.placement}</p></div><button onClick={()=>void remove(addon.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={15}/></button></article>)}{!addons.length&&<p className="text-sm text-slate-500">Belum ada add-on.</p>}</div><form onSubmit={add} className="mt-5 border-t border-slate-100 pt-4"><select value={type} onChange={e=>setType(e.target.value)} className="min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm">{types.map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select><input name="title" placeholder="Judul add-on" className="mt-2 min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"/><select name="placement" className="mt-2 min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="after_content">Setelah konten</option><option value="before_content">Sebelum konten</option></select>{["gallery","image_slider"].includes(type)&&<select required value={galleryId} onChange={e=>setGalleryId(e.target.value)} className="mt-2 min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="">Pilih gallery</option>{galleries.map(gallery=><option key={gallery.id} value={gallery.id}>{gallery.name}</option>)}</select>}{type==="pdf_viewer"&&<label className="mt-2 flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-300 p-4 text-sm"><input type="file" accept="application/pdf" className="sr-only" onChange={e=>{void uploadPdf(e.target.files?.[0]);e.target.value="";}}/><UploadCloud size={17}/>{pdfPath?"PDF siap":"Upload PDF"}</label>}<textarea value={config} onChange={e=>setConfig(e.target.value)} rows={3} aria-label="Config JSON add-on" className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-mono text-xs"/><button className="mt-2 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-violet-600 text-sm font-semibold text-white"><Plus size={16}/> Tambah add-on</button></form>{message&&<p className="mt-3 text-xs text-violet-700">{message}</p>}</section>}
