"use client";
import { FormEvent, useEffect, useState } from "react";
import { ShieldCheck, UserPlus, Users } from "lucide-react";
import { AppSidebar } from "@/components/app-sidebar";

type Site = { id: string; name: string }; type Role = { id: string; email: string; role: string; sites: { name: string; domain: string }[] | null };
export default function TeamPage() {
  const [roles, setRoles] = useState<Role[]>([]); const [sites, setSites] = useState<Site[]>([]); const [message, setMessage] = useState("");
  async function load() { const [roleResponse, siteResponse] = await Promise.all([fetch("/api/cms/team"), fetch("/api/cms/sites")]); const roleBody = await roleResponse.json().catch(() => null); const siteBody = await siteResponse.json().catch(() => null); if (roleResponse.ok) setRoles(roleBody?.data ?? []); else setMessage(roleBody?.error ?? "Tim tidak dapat dimuat."); if (siteResponse.ok) setSites(siteBody?.data ?? []); }
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, []);
  async function assign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const role = String(form.get("role")); const response = await fetch("/api/cms/team", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), role, siteId: role === "admin" ? null : form.get("siteId") }) }); const body = await response.json().catch(() => null); setMessage(response.ok ? "Role berhasil ditambahkan." : body?.error ?? "Role gagal ditambahkan."); if (response.ok) { event.currentTarget.reset(); void load(); } }
  return <main className="min-h-screen bg-[#f8fafc] p-5 md:p-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[240px_1fr]"><AppSidebar/><section className="min-w-0"><p className="text-sm font-medium text-blue-600">Akses</p><h1 className="mt-1 text-3xl font-bold">Tim dan role</h1><p className="mt-1 text-sm text-slate-500">Atur akses admin global, editor, dan writer per website.</p><div className="mt-7 grid gap-6 xl:grid-cols-[1fr_340px]"><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><Users size={19} className="text-blue-600"/><h2 className="font-semibold">Role aktif</h2></div><div className="divide-y divide-slate-100">{roles.map((item) => <div key={item.id} className="flex items-center gap-3 p-5"><span className="rounded-xl bg-slate-100 p-2"><ShieldCheck size={18}/></span><div className="min-w-0 flex-1"><p className="font-semibold">{item.email}</p><p className="mt-1 text-xs text-slate-500">{item.sites?.[0]?.name ?? "Semua website"}</p></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{item.role}</span></div>)}{!roles.length && <p className="p-10 text-center text-sm text-slate-500">Belum ada role.</p>}</div></section><form onSubmit={assign} className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Tambah role</h2><label className="mt-4 block text-sm font-medium">Email akun Auth<input required name="email" type="email" placeholder="writer@example.com" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3"/></label><label className="mt-4 block text-sm font-medium">Role<select name="role" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3"><option value="writer">Writer</option><option value="editor">Editor</option><option value="admin">Admin global</option></select></label><label className="mt-4 block text-sm font-medium">Website (editor/writer)<select name="siteId" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3"><option value="">Pilih website</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><button className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><UserPlus size={17}/> Tambah role</button></form></div>{message && <p className="mt-5 rounded-xl bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}</section></div></main>;
}
